### ISSUE TITLE
[Bug] When using Fluent API and setting the key on the column, that column is displayed twice in the table

### ISSUE THREAD

**Issue by viperet** [Laravel-Backpack/CRUD#4500]
# Bug report

When using Fluent API and setting the key on the column, that column is displayed twice in the table.

### What I did

```
    protected function setupListOperation()
    {
        CRUD::column('name')->key('name_1');
```

### What I expected to happen

I expect to see one column named 'name' and key 'name_1'

### What happened

Two columns are added, one with key 'name', and the other with key 'name_1'.

### What I've already tried to fix it

Switching to array syntax to add columns fixes the issue. Maybe that should be documented in the Fluid API docs?

### Is it a bug in the latest version of Backpack?

Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.1.7 (cli) (built: Jun 23 2022 07:15:05) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.7, Copyright (c) Zend Technologies
    with Xdebug v3.1.5, Copyright (c) 2002-2022, by Derick Rethans

### LARAVEL VERSION:
v9.14.1@2ca86f96118635a79ee3389013ccab110ae14bea

### BACKPACK VERSION:
5.0.19@a71715d51a0bd2827d535deb407761ee9252d04
<img width="413" alt="Admins :: Rankpay Admin Panel 2022-07-06 16-21-04" src="https://user-images.githubusercontent.com/725651/177560225-cec5f612-eab7-4892-92b6-edb03b20b0b5.png">
4

**Comment by pxpm** [comment]
Hey @viperet it's indeed an unintended behaviour. 

I am pretty sure I know what's happening I will implement a solution to fix it, but my real question is:
- What's your usecase that you need to change column `key` ? 

Thanks for the report 🙏

**Comment by viperet** [comment]
@pxpm I don't have a real use case for changing key, found this bug when working on server-side export operation and did tests to make sure it works with all edge-case configurations.

**Comment by pxpm** [comment]
Thanks @viperet . 

Anyway it's a bug that must be fixed. 
And ... You will be happy to know (I hope) that the next version of Backpack (5.2 probably out next week) will have an ExportOperation for server-side export 👍 

Cheers

**Comment by tabacitu** [comment]
Thanks for reporting this @viperet 🙏

I've just merged Pedro's PR, it'll be available with a `composer update` starting Monday, when we tag it along with other bug fixes.

Thanks again, keep 'em coming!

**Comment by viperet** [comment]
I think the easiest solution is to only allow to set key in the constructor as a second optional parameter:

```
CRUD::column('name', 'key');
```

**Comment by pxpm** [comment]
@viperet the PR is merged but not tagged yet, I think that is the issue here I tried now with:

```php
CRUD::column('owner')->key('owner');
CRUD::column('owner')->key('owner_2');
CRUD::column('owner')->key('owner_3');
```
and it worked I guess:

![image](https://user-images.githubusercontent.com/7188159/177828663-a9c4b377-502e-490a-9585-142400aba9b0.png)

**Comment by tabacitu** [comment]
Yup - @viperet  to _actually_ get it before we tag it on Monday, you can do `composer require backpack/crud:"v5-dev as 5.1.5"` - that will pull the `v5` branch directly. You should then undo this, after Monday.

**Comment by viperet** [comment]
@tabacitu before that for my test I just manually applier PR to sources in /vendor/backpack/crud, after a message from @pxpm thought "oh, maybe there are other changes that I don't have that make a difference", so I installed latest v5 branch from git - the same result.
Today I installed using your command (had to change it to `composer require backpack/crud:"v5.x-dev as 5.1.5"`).
Still can't get the same results as in @pxpm screenshot.
Will probably wait till the official release and then will write some unit tests.

**Comment by pxpm** [comment]
Hello @viperet 

I revisited this today and could reproduce your issue, my solution was not final and was not working properly.

I've submitted https://github.com/Laravel-Backpack/CRUD/pull/4548 with a fix that I think will solve this problem for good.

Would you mind give it a try and let us know your results ?

Thanks and sorry for the bad experience here 😿
