### ISSUE TITLE
[Bug] With two select2 in the same subfield, options of the dependent subfield are disabled.

### ISSUE THREAD

**Issue by CamusMX7** [Laravel-Backpack/CRUD#4544]
# Bug report

### What I did

I added an extra subfield to filter my pivotSelect with a category. 
```php
$this->crud->addField([
'name'          => 'precios',
'type'          => "relationship",
'pivotSelect'  => [
    'ajax' => true,
    'inline_create' => [ 'entity' => 'precio' ],
    'data_source' => backpack_url('presupuesto/fetch/precio'),
    'minimum_input_length' => 0,
    'wrapper' => [
        'class' => 'col-md-3 order-2'
    ],
    'attributes' => [
        'required'  => 'required',
    ],
    'dependencies'  => ['categoria_precio_id']
],
'subfields'     => [
    [
        'name' => 'categoria_precio_id',
        'type' => 'relationship',
        'label' => 'Categoría',
        'wrapper' => [
            'class' => 'form-group col-md-2 order-1',
        ],
        'dependencies'  => ['tipo'],
        'ajax' => true,
        'data_source' => backpack_url('presupuesto/fetch/categoria-precio'),
        'minimum_input_length' => 0
    ],
    [
        'name' => 'costo',
        'type' => 'text',
        'label' => 'Costo Unitario',
        'wrapper' => [
            'class' => 'form-group col-md-1 order-3',
        ],
    ],
    [
        'name' => 'cantidad',
        'type' => 'text',
        'wrapper' => [
            'class' => 'form-group col-md-1 order-4',
        ],
    ],
    [
        'name' => 'duracion',
        'type' => 'text',
        'wrapper' => [
            'class' => 'form-group col-md-2 order-5',
        ]
    ],
    [
        'name' => 'costo_final',
        'type' => 'text',
        'label' => 'Costo',
        'wrapper' => [
            'class' => 'form-group col-md-1 order-6 costo_final',
        ],
        'attributes' => array('readonly' => 'readonly', 'disabled' => 'disabled')
    ],
],
'tab'           => "Precios",
'force_delete'  => true]);
```

### What I expected to happen

Allow me to select any option in either select of each subfield

### What happened

If in subfield 1 (category) I selected the element with ID=1, in subfield  2 (price) I cannot select the element with ID=1, even though they are fields related to different models.

![ejemplo_form](https://user-images.githubusercontent.com/107073227/180289081-9e6fcd29-271b-44f7-97d1-c65c1aed96ff.png)

### What I've already tried to fix it

I looked for other alternatives like enabling all the select options with javascript code

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

PHP 8.1.2
Laravel 9.1.0
Backpack 5.1.3

### Others

Related to the topic, I hope you can help me with this problem:
[https://stackoverflow.com/questions/73059630/how-to-override-the-select2-action-that-disables-subfield-options-selected-in-a](url)
I need no option to be disabled in any of the subfields select2.
Can the option to disable previously selected items be configured in backpack?
@pxpm could you help me with this topic?
Thanks

**Comment by pxpm** [comment]
Hello @CamusMX7 

I could confirm your issue and I have already submited a PR to fix it. 

It should be merged in the next release. 

Thanks again for the report and sorry for the bad experience. 

Cheers

**Comment by CamusMX7** [comment]
Thanks. @pxpm  Sorry for the bother, could you help me with the problem on [stackoverflow](https://stackoverflow.com/questions/73059630/how-to-override-the-select2-action-that-disables-subfield-options-selected-in-a)? Is it possible that none of the select2 options are deactivated so that I can store in my pivot table several pairs of foreign keys that are the same but with the other subfields different?
I already did some tests forcing the save but it only saves a record.
I would really appreciate it if you could support me.

**Comment by CamusMX7** [comment]
Please, could someone indicate where I can write to receive official support or what is the official process? Perhaps wanting to take advantage of the moment here is not the right thing to do and I apologize.
Mainly I would like to know if the field of type relationship that repeats subfields and stores in a pivot table allows me to add several pairs of repeated foreign keys. That is, as in the example:

![tabla2](https://user-images.githubusercontent.com/107073227/180589894-8683e97c-44fa-413e-a374-02ed283ff822.JPG)

Since it deactivates the select2 options for me and if I try to force it, it only updates or saves a record. I have tried some things in my model structure like or explain on stackoverflow.
I don't know if the field supports me to create a model for my pivot table.

Thanks

**Comment by pxpm** [comment]
Hello @CamusMX7 
That's not how M-M are designed to work, so I think you will be safe using the repeatable field directly (not via relationship) so you need to define `type => repeatable` then override the create/update .methods on controller and do your own saving process. 
Properly using a relationship there is no way you will endup with duplicated pivots, you could/should probably have a model of SomethingCosts and then use the pivot to link with the choose cost.

The easiest way is the first I described. 

Cheers

**Comment by tabacitu** [comment]
> That's not how M-M are designed to work, so I think you will be safe using the repeatable field directly (not via relationship) so you need to define type => repeatable then override the create/update .methods on controller and do your own saving process.

Yup, that sounds best to me too.

---

I've just merged and tagged Pedro's PR. So a `composer update backpack/pro` should get you 1.2.1 which has this fixed. Let us know if that's not the case and we'll reopen.

Cheers!

**Comment by CamusMX7** [comment]
@pxpm Thanks for clarifying with your comments. 
There are several things that I already had resolved and they only added the new requirement to be able to save repeated elements by changing quantity and cost. I'll check how I can adjust it.

On the other hand, I updated backpack/crud and backpack/pro but I still get the reported error.
![error_prosigue](https://user-images.githubusercontent.com/107073227/180847726-5bdf00d3-2819-4841-bfc0-efb9a0ec9690.JPG)

Cheers

**Comment by pxpm** [comment]
Hello @CamusMX7 

Aren't you overriding `repeatable.blade.php` ? 

I was able to reproduce your issue, but after the PR I submitted I am no longer able to reproduce it:
![image](https://user-images.githubusercontent.com/7188159/180972109-16cc9fc6-db90-4396-ac2f-c1ba442a9c57.png)

This is my MM definition:
```php
[
                'name'    => 'dummyproducts',
                'label'   => 'BelongsToMany (n-n) <small>+ subfields for pivot table</small>'.backpack_new_badge(),
                'wrapper' => [
                    'class' => 'form-group col-md-4',
                ],
                'pivotSelect' => [
                    'ajax' => true,
                    'data_source' => backpack_url('monster/fetch/product'),
                    'minimum_input_length' => 0,
                    'wrapper' => [
                        'class' => 'form-group col-md-6',
                    ],
                ],
                'subfields' => [
                    [
                        'name'    => 'notes',
                        'type'    => 'relationship.fetch',
                        'model' => Product::class,
                        'minimum_input_length' => 0,
                        'multiple' => false,
                        'data_source' => backpack_url('monster/fetch/product'),
                        'wrapper' => [
                            'class' => 'form-group col-md-6',
                        ],
                    ],
                ],
                'tab'   => 'Relationship',
            ],
```

Cheers

**Comment by CamusMX7** [comment]
Hello @pxpm 
I am now using the path that you suggested and it seems that everything is going well and I achieved my goal, thanks.

But in order not to leave the initial problem in doubt, I adjusted my field definition similar to yours and it is true, it seems to work correctly. But in your example, if you select "notes" first and only after that try to select "dummyproducts" with the same ID, then it won't let you (I guess). I understand that the selection order is from left to right, but it should work even if you select the subfield first and then the "pivotSelect".

For example in my particular case, the new requirement was to add the subfield "category" to be able to filter the pivotSelect "prices", that's why I added the css class "order-2" to the pivotSelect and the css class "order-1" to the "category" subfield, then I first select the category subfield and then the "pivotSelect" prices and if I choose the category subfield with ID = 1, it does not allow me to select the element with ID = 1 in the "pivotSelect".

I hope that helps.

Cheers

**Comment by pxpm** [comment]
Hello @CamusMX7 

Whatever I select in Notes has not effect on what I can select in DummyProduct (the pivotSelect). 

The way they are diferentiated is that `is-pivot-select` is true in one of them, and false in the other. 

If you want to filter the pivotSelect with the category value you should be able to add in the pivotSelect definition: `include_all_form_fields => true` or `include_all_form_fields => ['category_id']` if you only need that one, and in your `fetch()` function you should define the query attribute to filter the returned results the way you want: https://backpackforlaravel.com/docs/5.x/crud-operation-fetch#how-to-use-1 
This may help on the filtering results: https://backpackforlaravel.com/docs/5.x/crud-how-to#how-to-add-a-relationship-field-that-depends-on-another-field

Cheers

**Comment by CamusMX7** [comment]
Excuse me @pxpm , I hope not to confuse the main point with my particular comments. I have my fetch() function, filtering, dependency and everything else working fine.
-------------------------------------------------- ------------------------------------------------------------------------------------
What I mean is that if I reproduce your example and select first "dummyproducts" (id=1) and then "notes" (id=1) it now works fine. BUT, if I first select "notes" (id=1) and then try to select "dummyproducts" (id=1) it is not possible, the option appears disabled.

If necessary I'll record a gif or something to show the example as soon as I have some time.

**Comment by pxpm** [comment]
@CamusMX7 I cannot reproduce that, like I told you, anything i select in notes is selectable in other notes and in the dummy products. 

Cheers

**Comment by CamusMX7** [comment]
@pxpm Would it be possible could you post your example to see it working? 
https://demo.backpackforlaravel.com/admin/monster/140/edit#relationship

Currently "notes" is a text field.

![pagina_ejemplo](https://user-images.githubusercontent.com/107073227/181103580-995bb19d-11c4-4e02-9d5c-8ec2b8daad4d.JPG)


Sorry for the inconvenience, just to validate and then check for myself what the difference is.

**Comment by pxpm** [comment]
Hello @CamusMX7 

I've posted the example above, I changed the notes field:

```php
'subfields' => [
                    [
                        'name'    => 'notes',
                        'type'    => 'relationship.fetch',
                        'model' => Product::class,
                        'minimum_input_length' => 0,
                        'multiple' => false,
                        'data_source' => backpack_url('monster/fetch/product'),
                        'wrapper' => [
                            'class' => 'form-group col-md-6',
                        ],
                    ],
                ],
```

Let me know, cheers.

**Comment by CamusMX7** [comment]
In https://demo.backpackforlaravel.com/admin/monster/139/edit#relationship I didn't see the change, but I installed the demo locally and did the tests.
Just as you mentioned it works on both sides, the problem is then in my code, I already checked a lot and I can't find what's happening.
I adjusted my field definition similar to yours, but still seeing the same issue:

`        $this->crud->addField([
            'name'          => 'precios',
            'label'         => 'Servicios',
            'wrapper' => [
                'class' => 'form-group col-md-12',
            ],
            'pivotSelect'  => [
                'ajax' => true,
                'data_source' => backpack_url('orden-trabajo/fetch/precio'),
                'minimum_input_length' => 0,
                'wrapper' => [
                    'class' => 'form-group col-md-3 order-2'
                ]
            ],
            'subfields'     => [
                [
                    'name' => 'categoria_precio_id',
                    'type' => 'relationship.fetch',
                    'model'       => "App\Models\CategoriaPrecio", 
                    'minimum_input_length' => 0,
                    'multiple' => false,
                    'data_source' => backpack_url('orden-trabajo/fetch/categoria-precio'),
                    'wrapper' => [
                        'class' => 'form-group col-md-2 order-1',
                    ],
                ],
            ],
            'tab'           => "Relationship"
        ]);`
        
It's a very rare case, but since I'm now using "type => repeatable" I don't want to go any further.
Thanks for the patience and hard work.

cheers.
