### ISSUE TITLE
colspan issue in `ListOperation`

### ISSUE THREAD

**Issue by EGYWEB-Mohamed** [Laravel-Backpack/CRUD#4951]
# Bug report

### What I did

responsive table

### What I expected to happen

![image](https://user-images.githubusercontent.com/23424932/222141836-b85ed106-c192-48c2-b4d1-e9b62856faee.png)

### What happened

![image](https://user-images.githubusercontent.com/23424932/222141900-c6cd3f7e-1484-4ff2-8fd5-1f08e1f6adf8.png)

and I noticed from inspect element there's colspan added to the first row

![image](https://user-images.githubusercontent.com/23424932/222142112-68624163-5c1b-4476-89d4-36e9122c8234.png)

### What I've already tried to fix it

N/A

### Is it a bug in the latest version of Backpack?

Yes

### PHP VERSION:
PHP 8.1.7 (cli) (built: Jun 16 2022 12:46:39) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.7, Copyright (c) Zend Technologies
    with the ionCube PHP Loader v12.0.5, Copyright (c) 2002-2022, by ionCube Ltd.

### LARAVEL VERSION:
v9.52.4@9239128cfb4d22afefb64060dfecf53e82987267

### BACKPACK PACKAGE VERSIONS:
backpack/crud: 5.5.1
backpack/devtools: 1.3.2
backpack/editable-columns: 2.1.1
backpack/filemanager: 2.0.0
backpack/generators: 3.3.14
backpack/permissionmanager: 6.0.16
backpack/pro: 1.6.0

**Comment by tabacitu** [comment]
Hmm... I'm not sure I understand @EGYWEB-Mohamed . Can you please rephrase? Everywhere I have `responsiveTable` enabled... it works... there's no such visual bug like you showed in your screenshot. How did you do that? What did you do different - that's the part I don't understand.

Is it happening anywhere in our demo https://demo.backpackforlaravel.com/admin/article?

Cheers!

**Comment by EGYWEB-Mohamed** [comment]
@tabacitu after too many hours of investigation I found it causes when there are too many columns and `responsiveTable => true` in `list.php` and what is causing is `showEntryCount => true` when it is true the problem is fixed by itself 
![image](https://user-images.githubusercontent.com/23424932/222993056-a4473033-54c1-4950-8fa8-e47088845ea2.png)

and when it changes to false,  this weird problem appears 
![image](https://user-images.githubusercontent.com/23424932/222993075-ec53bd6f-267c-428d-ad10-d70e1369298e.png)

**Comment by karandatwani92** [comment]
Hi, @pxpm  Following the above instructions I'm unable to reproduce this error. Please have a look.
Neither I could find anything in `src` related to `colspan`
Let me know what you find then we fix it.

**Comment by adriannuta** [comment]
I can confirm this bug as well: it reproduces with showEntryCount=false and on small resolutions. It does not reproduce if responsive table is disabled.  If if you redrawn the result (e.g. using no. of entries per page dropdown), it renders fine.

**Comment by mint-ws** [comment]
I see this issue has been added to the Todo list but for what it's worth, I'm experiencing the exact same issue. First row gets a colspan on a responsive table.

showEntryCount = false:
<img width="958" alt="image" src="https://github.com/Laravel-Backpack/CRUD/assets/15357098/f83c4c58-daf8-49c9-8cf9-d1ca5cac2a13">

showEntryCount = true: 
<img width="1025" alt="image" src="https://github.com/Laravel-Backpack/CRUD/assets/15357098/0a79334d-145a-4ddc-9749-5975c85ab981">

Huge thank you to @EGYWEB-Mohamed for figuring out the fix.

**Comment by EGYWEB-Mohamed** [comment]
@mint-ws 
You're welcome! I'm glad to hear that It's always great when people come together to help each other out.

**Comment by pxpm** [comment]
Hey guys. 

Thanks for the report and solution @EGYWEB-Mohamed and everyone who participated here.

I hope that we fixed this somehow 🤷 , I was totally unable to reproduce this in our demo:

![image](https://github.com/Laravel-Backpack/CRUD/assets/7188159/8bf1441b-b757-4626-8fe1-3c4465a139ae)

![image](https://github.com/Laravel-Backpack/CRUD/assets/7188159/9a1185b9-6e56-4ee4-9c4b-db78c7aa3575)

I am preemptively closing this, but if you guys still experience the issue, please provide me the clear steps on how I can reproduce it, ideally in our demo, or in a clean install.

Cheers

**Comment by zeknoss** [comment]
Hello,
I can also confirm that disabling the row count on the list view makes the first row of table render the first column with wrong colspan value.

@pxpm I believe you can reproduce this issue using the `tabler` theme.

**Comment by K-Mazur** [comment]
Hi,

I can confirm that I've also encountered this bug. Not sure if that helps or not, but it appears that when we set `showEntryCount` to `false`, then in the `ListOperation` trait, the `$totalEntryCount` and `$filteredEntryCount` are set up differently, and once filteredEntryCount is 0, the problem occurs.
https://github.com/Laravel-Backpack/CRUD/blob/1fe921d1b1dbabafcad587e49582e13c453cf9ae/src/app/Http/Controllers/Operations/ListOperation.php#L107-L114

**Comment by pxpm** [comment]
I've tried really hard to reproduce this again, but unfortunatelly I am still not able. 

I've tried enable/disable `showEntryCount`, I've tried forcing the `filteredEntryCount` to be 0 as suggested by @K-Mazur, I've tried enabled and disabled responsive table, nothing yielded those results. 

![image](https://github.com/user-attachments/assets/6172a817-332c-48fd-910a-eefca4000e35)
![image](https://github.com/user-attachments/assets/561a102d-b301-492f-a731-974092fbef25)
![image](https://github.com/user-attachments/assets/6ab0d77a-4292-4b89-a48d-a9fd372de0f2)


![image](https://github.com/user-attachments/assets/e75c3725-3630-4690-84dc-7a41fc24d6dd)
![image](https://github.com/user-attachments/assets/83a72619-acc7-4869-98e6-6b04bdfb5815)
![image](https://github.com/user-attachments/assets/11bb1ecd-2a3e-442a-871b-aae28554a4dc)

One thing I noticed from your screenshots is that the search bar on the top right has rounded borders, while we use for some time square borders. Is it possible that you guys have the `list.blade.php` and or `datatables_logic.blade.php` overwritten in your projects and are not loading the backpack view ? 

I would really love to be able to reproduce this, if anyone can setup a reproduction repo I can use, I will glady fix this, until then I am totally in the dark here 😞 

Going to keep this open for a while hoping someone can provide me a way to reproduce this. 

Cheers

**Comment by mint-ws** [comment]
Hi there, since I stopped using backpack some time ago I can't provide a sample.
I didn't override `list.blade.php` and or `datatables_logic.blade.php` but I do see from your screenshots that the page numbers in the pagination links (bottom right) still don't show when showEntryCount=false. If that's not intentional maybe therein lies a clue. Sorry I can't be more helpful.

**Comment by pxpm** [comment]
> Hi there, since I stopped using backpack some time ago I can't provide a sample. I didn't override `list.blade.php` and or `datatables_logic.blade.php` but I do see from your screenshots that the page numbers in the pagination links (bottom right) still don't show when showEntryCount=false. If that's not intentional maybe therein lies a clue. Sorry I can't be more helpful.

Thanks @mint-ws, appreciate your feedback. Not showing the page numbers when `showEntryCount` is false is a **feature**. To display the page numbers we would need to do the count to know how many pages of information there are so it would defeat the purpose of not doing the count on the first place. 

Thanks a lot for your input, I will wait to see if someone else have a better insight 🙏 

Cheers

**Comment by zeknoss** [comment]
> > Hi there, since I stopped using backpack some time ago I can't provide a sample. I didn't override `list.blade.php` and or `datatables_logic.blade.php` but I do see from your screenshots that the page numbers in the pagination links (bottom right) still don't show when showEntryCount=false. If that's not intentional maybe therein lies a clue. Sorry I can't be more helpful.
> 
> Thanks @mint-ws, appreciate your feedback. Not showing the page numbers when `showEntryCount` is false is a **feature**. To display the page numbers we would need to do the count to know how many pages of information there are so it would defeat the purpose of not doing the count on the first place.
> 
> Thanks a lot for your input, I will wait to see if someone else have a better insight 🙏
> 
> Cheers

Hey @pxpm, which theme are you using in your tests?

**Comment by zeknoss** [comment]
I'll try to come up with a reproduction guide for you, asap

**Comment by adriannuta** [comment]
> Hi,
> 
> I can confirm that I've also encountered this bug. Not sure if that helps or not, but it appears that when we set `showEntryCount` to `false`, then in the `ListOperation` trait, the `$totalEntryCount` and `$filteredEntryCount` are set up differently, and once `$filteredEntryCount` is 0, the problem occurs.
> 
> https://github.com/Laravel-Backpack/CRUD/blob/1fe921d1b1dbabafcad587e49582e13c453cf9ae/src/app/Http/Controllers/Operations/ListOperation.php#L107-L114
 Setting      $filteredEntryCount to 0 is the problem. If the result set has one row, the  'search' response will be "recordsTotal": 10,   "recordsFiltered": 0,  "actual_total": 1 - this cause that colspan (I think dt tries to draw the 'No results found' because of   recordsFiltered value and the rows drawing doesn't clear that colspan).   $filteredEntryCount should be set to $entries->count() instead.

**Comment by pxpm** [comment]
thank you all, I was finally able to reproduce the issue and fix it 🙏 

A `composer update` should give you `5.7.46` of `backpack/crud` with the fix 👍 

Cheers
